name: app_bus
description: Central de Gestão, Monitoramento e Auditoria do Transporte Escolar - SEMEC.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Interface e Componentes Visuais (Híbrido)
  fluent_ui: ^4.15.1
  sidebarx: ^0.15.0
  fl_chart: ^0.66.2
  provider: ^6.1.5+1

  # Motores do Aplicativo Mobile (Ponta)
  geolocator: ^10.1.0
  uuid: ^4.3.3
  sqflite_sqlcipher: ^3.2.1
  connectivity_plus: ^5.0.2

  # Comunicação e Utilitários de Rede
  http: ^1.6.0

  # Utilitários de Controle de Janela Nativa (Windows)
  window_manager: ^0.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

dependency_overrides:
  intl: ^0.20.2

flutter:
  uses-material-design: true