name: bus_desktop
description: Sistema Inteligente de Monitoramento do Transporte Escolar - SEMEC Conceição do Araguaia
publish_to: 'none'
version: 1.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- BANCO DE DADOS E PERSISTÊNCIA ---
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1

  # --- HARDWARE E INTELIGÊNCIA ARTIFICIAL ---
  camera: ^0.10.5+5
  google_mlkit_face_detection: ^0.11.0
  tflite_flutter: ^0.10.0

  # --- UTILIDADES, REDE E PDF ---
  connectivity_plus: ^5.0.2
  intl: ^0.18.1
  #pdf: ^3.10.7
  #printing: ^5.11.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # --- CONFIGURAÇÃO DOS ASSETS ---
  # IMPORTANTE: Você deve criar fisicamente as pastas assets/models e assets/images
  # e colocar os arquivos lá, caso contrário o Flutter não compilará.
  # assets:
   # - assets/models/mobilefacenet.tflite
   # - assets/images/